language: php
sudo: required
php:
  - 7.2

addons:
  apt:
    packages:
    - "python3"
    - "python3-pip"

services:
  - docker

before_script: composer install

script: 
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs --standard=psr2 app