language: php
sudo: required
php:
  - 7.2
python:
  - 3.4

services:
  - docker

before_script: composer install

script: 
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs --standard=psr2 app

deploy:
  on:
    branch: master
  provider: script
  script: bash docker-release.sh