version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: fpm.Dockerfile
    volumes:
    - ./:/app
    links:
    - mysql
    - s3
  php-worker:
    build:
      context: ./
      dockerfile: cli.Dockerfile
    volumes:
    - ./:/app
    links:
    - mysql
    - s3
  web:
    image: nginx:latest
    ports:
    - "8000:80"
    volumes:
    - ./:/app
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
    - php
  s3:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: s3user
      MINIO_SECRET_KEY: s3passs3pass
    command: server /data
  mysql:
    image: mysql:5.6
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass